using System.Collections;
using System.Collections.Generic;
using Unity.VisualScripting;
using UnityEngine;
using UnityEngine.UIElements;

public class PlayerMove : MonoBehaviour
{
    public Animator animator;
    public bool isGrounded;
    public bool isSlide;
    public bool isDie;
    public int jumpCount = 0;
    public int maxJumpCount = 2;
    public float jumpForce = 10f;
    private Rigidbody2D _rigidbody2D;
    public int maxHp = 100;
    public int currentHp;
    public float tickRate = 1f;
    public int tickDamage = 1;
    private float tickTimer = 0f;
    private BoxCollider2D playerCollider;
    private Vector2 originalColliderSize;
    private Vector2 originalColliderOffset;
    public Vector2 sliderColliderSize = new Vector2(1f, 0.8f);
    public Vector2 sliderColliderOffset = new Vector2(0f, -0.4f);
    public float dieOffsetY = -15f;
    public bool isHit = false;
    public bool isInvincible = false; // ë¬´ì 
    public float invincibleDuration = 1f; // ë¬´ì  ì§€ì†ì‹œê°„
    public float invincibleTime = 0f;
    public float hitAnimeDuration = 0.8f; // hitì• ë‹ˆë©”ì´ì…˜ ì§€ì†ì‹œê°„
    private Coroutine invCoroutine = null;


    //public LayerMask groundLayer; // ë ˆì´ì–´ ì„¤ì •
    //public float groundCheckDistance = 0.1f; // raycast ê¸¸ì´ 
    //public Vector2 groundCheckOffset = new Vector2(0f, -0.6f); // ë ˆì´ì € ì˜ëŠ” ìœ„ì¹˜ në§Œí¼ ë‚´ë¦¼

    // Start is called before the first frame update
    void Start()
    {
        _rigidbody2D = GetComponent<Rigidbody2D>();
        animator = GetComponentInChildren<Animator>();
        playerCollider = GetComponent<BoxCollider2D>();
        originalColliderSize = playerCollider.size;
        originalColliderOffset = playerCollider.offset;
        currentHp = maxHp;
        isDie = false;
    }

    // Update is called once per frame
    void Update()
    {
        //GroundCheck();

        if (maxJumpCount > jumpCount && (Input.GetButtonDown("Jump") || Input.GetKeyDown(KeyCode.X)) && !isDie) // ë²„íŠ¼ ì´ë¦„ì— ë§ê²Œ ë³€ê²½
        {
            Jump();
        }

        if (!isSlide && Input.GetKey(KeyCode.C) && !isDie) // || Input.GetButtonDown("Slide") ì¶”í›„ ìŠ¬ë¼ì´ë“œ ë²„íŠ¼ ì¶”ê°€í•˜ë©´ ê°™ì´ ì¶”ê°€
        {
            Slide();
        }

        if (isSlide && Input.GetKeyUp(KeyCode.C) && !isDie)
        {
            isSlide = false;
            playerCollider.size = originalColliderSize;
            playerCollider.offset = originalColliderOffset;
        }

        if (transform.position.y < dieOffsetY)
        {
            Die();
        }



        animator.SetBool("isGrounded", isGrounded);
        animator.SetBool("isJump", !isGrounded);
        animator.SetBool("isSlide", isSlide);
        animator.SetBool("isDie", isDie);

        tickTimer += Time.deltaTime;
        if (tickTimer >= tickRate)
        {
            tickTimer = 0f;
            TakeDamage(tickDamage);
        }

        if (currentHp <= 0)
        {
            Die();
        }



    }

    void Jump()
    {
        _rigidbody2D.velocity = new Vector2(_rigidbody2D.velocity.x, jumpForce);
        jumpCount++;
        isGrounded = false;
    }

    void Slide()
    {
        if (!isSlide && isGrounded)
        {
            isSlide = true;
            animator.SetTrigger("isSlide");
            playerCollider.size = sliderColliderSize;
            playerCollider.offset = sliderColliderOffset;
        }

    }
    private void OnCollisionEnter2D(Collision2D collision)
    {
        if (collision.gameObject.CompareTag("Ground"))  // íƒœê·¸ Ground ë¡œ
        {
            Vector3 vector3 = _rigidbody2D.velocity;   // ê²¹ì¹˜ê¸° ë¬´í•œì í”„ ë°©ì§€
            if (vector3 == Vector3.zero)
            {
                isGrounded = true;
                jumpCount = 0; // ì°©ì§€ í›„ ì¹´ìš´íŠ¸ ì´ˆê¸°í™”
            }
        }
    }
    public void TakeDamage(int damage)
    {
        if (isInvincible || isHit)
        {
            Debug.Log("ë¬´ì ");
            return;
        }

        currentHp -= damage;
        if (currentHp <= 0)
        {
            currentHp = 0;
            Die();
            return;

        }

        if (invCoroutine != null)
        {
            StopCoroutine(invCoroutine);

        }

        if (damage > tickDamage) // í‹±ë€ì— ì˜í•œ ë¬´ì ë°œìƒ ë°©ì§€
        {
            invCoroutine = StartCoroutine(OnHitRoutine());
        }

    }
    public void Heal(int heal)
    {
        currentHp += heal;
        currentHp = Mathf.Min(currentHp, maxHp);
        Debug.Log("ì²´ë ¥ íšŒë³µë¨: " + currentHp);
    }

    public void Die()
    {
        if (isDie) return;
        isDie = true;
        currentHp = 0;
        _rigidbody2D.velocity = Vector2.zero;

        Debug.Log("Player Die");
        animator.SetTrigger("isDie");
        _rigidbody2D.velocity = new Vector2(_rigidbody2D.velocity.x, jumpForce * 1.5f);
        GameManager.instance.GroundStop();
        //ì• ë‹ˆë©”ì´ì…˜ ì¶”ê°€ ì˜ˆì •? í˜¹ì€ ë°”ë¡œ ê²°ê³¼ì°½?

        GameManager.instance.EndGame();
    }

    private IEnumerator GotoResultScene()
    {
        GameManager.instance.EndGame();

        // ğŸ”¹ 2. 0.5ì´ˆ ì •ë„ ê¸°ë‹¤ë¦° í›„ ê²°ê³¼ ì”¬ìœ¼ë¡œ ì´ë™
        yield return new WaitForSeconds(0.5f);
        UnityEngine.SceneManagement.SceneManager.LoadScene("ResultScene");
    }

    public void TryJump() //ëª¨ë°”ì¼ ë²„íŠ¼ ìš© ë©”ì¨ë“œ
    {
        if (maxJumpCount > jumpCount && isGrounded && !isDie)
        {
            Jump();
        }
    }

    public void TrySlide()
    {
        if (!isSlide && isGrounded && !isDie)
        {
            Slide();
        }

    }
    IEnumerator OnHitRoutine()
    {
        isHit = true;
        isInvincible = true;
        animator.SetBool("isHit", true);
        yield return new WaitForSeconds(hitAnimeDuration);
        animator.SetBool("isHit", false);
        isHit = false;
        yield return new WaitForSeconds(invincibleDuration - hitAnimeDuration); // anim ì‹œê°„ ì´í›„ ë‚¨ì€ ë¬´ì ì‹œê°„ ì§€ì†
        isInvincible = false;
    }

}
